services:
  backend:
    build: .
    container_name: cloth_inventory_backend

    ports:
      - "8000:8000"

    env_file:
      - .env.render

    volumes:
      - .:/app

    restart: unless-stopped